export const listPackage = [
  {
    id: 1,
    name: "Basic",
    harga: 1000000,
    fitur: [
      "5 Halaman",
      "5 Hari Pengerjaan",
      "1x Revisi",
      "1 SEO Kerword",
      "5 Page SEO Dasar",
      "10 Upload Setup Gambar",
      "+3 Akun Email",
      "GRATIS SSL",
      "GRATIS DOMAIN .COM / .CO.ID",
      "Mobile Friendly",
    ],
  },
  {
    id: 2,
    name: "Basic",
    harga: 1750000,
    key: "Rekomendasi",
    fitur: [
      "5 Halaman",
      "5 Hari Pengerjaan",
      "1x Revisi",
      "1 SEO Kerword",
      "5 Page SEO Dasar",
      "10 Upload Setup Gambar",
      "+3 Akun Email",
      "GRATIS SSL",
      "GRATIS DOMAIN .COM / .CO.ID",
      "Mobile Friendly",
    ],
  },
  {
    id: 3,
    name: "Basic",
    harga: 2000000,
    fitur: [
      "5 Halaman",
      "5 Hari Pengerjaan",
      "1x Revisi",
      "1 SEO Kerword",
      "5 Page SEO Dasar",
      "10 Upload Setup Gambar",
      "+3 Akun Email",
      "GRATIS SSL",
      "GRATIS DOMAIN .COM / .CO.ID",
      "Mobile Friendly",
    ],
  },
];
